name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'test/**'
      - 'playground/**'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'test/**'
      - 'playground/**'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-node@v5
          with:
            node-version: 24
            registry-url: https://registry.npmjs.org/
        - run: npm ci
        - name: Prepare testing with the playground
          run: npm run dev:prepare
        - name: Test package
          run: npm run test
